language: scala
jdk:
  oraclejdk8

scala:
  - 2.12.10
  -
script:
  - sbt scripted
  -
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
  -
cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    -
notifications:
  email:
    recipients:
      - romaanankin@gmail.com

